name: Test project
on: 
    push:
        branches: 
            - main
            - dev
            - 'dev-*' # push on any branch with dev

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get codes
              uses: actions/checkout@v6
            
            - name: cache depency
            
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: dep-nodes-module-${{ hashFiles('**/package-lock.json')}}
            
            - name: Install NodeJS
              uses: actions/setup-node@v6
              with: 
                node-version: 24
            - name: Install dependecies
              run: npm ci

            - name: Running the test
              run: npm test
    




