name: Test project
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get codes
              uses: actions/checkout@v6
            
            - name: Install NodeJS
              uses: actions/setup-node@v6
              with: 
                node-version: 24
            - name: Install dependecies
              run: npm ci

            - name: Running the test
              run: npm test
    
    deploy: 
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v6

            - name: install NodeJS
              uses: actions/setup-node@v6
              with:
                node-version: 24
            - name: install dependency
              run: npm ci
            - name: build step
              run: npm run build




